<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-0T3LLVM" failures="5" tests="5" name="Custom Test" time="135.861" errors="0" timestamp="2023-02-27T21:03:02 EST">
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="24.458">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="22.55">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="22.117">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="22.669">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="23.208">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="0.0">
    <ignored/>
  </testcase> <!-- validAdminLogin -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserAnEmptyPassword" time="0.0">
    <ignored/>
  </testcase> <!-- validUserAnEmptyPassword -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- validUserInvalidPassword -->
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.0">
    <ignored/>
  </testcase> <!-- userLogin -->
  <testcase classname="com.exelenter.testcases.AddEmployeeTest" name="addEmployeeTest" time="0.0">
    <ignored/>
  </testcase> <!-- addEmployeeTest -->
</testsuite> <!-- Custom Test -->
